"""
2026/02/14: remove duplicated kanjis generated by buggy on-the-fly code
"""

from booktocards.kb import ColumnName, KnowledgeBase, TableName

kb = KnowledgeBase()

# For each source, drop duplicated kanjis if any
initial_count = len(kb.__dict__[TableName.KANJIS])
kb.__dict__[TableName.KANJIS].drop_duplicates(
    subset=[ColumnName.KANJI, ColumnName.SOURCE_NAME], inplace=True
)
final_count = len(kb.__dict__[TableName.KANJIS])
print(f"Removed {initial_count - final_count} duplicated kanjis.")

kb.save_kb(make_backup=True)
